[package]
name = "placeholder"
version = "0.1.0"
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]
edition = "2018"

[features]
simd-accel = ["encoding_rs/simd-accel"]

[dependencies]
encoding_rs = "0.8.16"